apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-go
spec:
  template:
    metadata:
      labels:
        app: helloworld-go
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/knative-sample/helloworld-go:160e4dc8
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: TARGET
          value: "serveless"

---

# curl -v -HHost:hello-go.default.example.com --resolve hello-go.default.example.com:31380:172.31.71.181 http://hello-go.default.example.com:31380